server:
  port: 8081

spring:
  application:
    name: ruleforge-console
  datasource:
    app:
      jdbcUrl:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 60000
        idle-timeout: 300000
        max-lifetime: 1200000
        leak-detection-threshold: 30000
        validation-timeout: 3000
        connection-test-query: SELECT 1
        pool-name: AppCloudSqlCP
    ruleforge:
      jdbcUrl:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 60000
        idle-timeout: 300000
        max-lifetime: 1200000
        leak-detection-threshold: 30000
        validation-timeout: 3000
        connection-test-query: SELECT 1
        pool-name: UruleCloudSqlCP
  servlet:
        multipart:
      max-file-size: 50MB
      max-request-size: 50MB

ruleforge:
  knowledgeUpdateCycleV2: 300
  isKnowledgeUpdateRemoteV2: false
  repository:
    dir: ./ruleforge-prod-console/data/riskruleforge
  exec:
    url: http://localhost:8082

# 延迟加载配置
lazy-load:
  enabled: true  # 是否启用延迟加载
  base-url:  # 数据源API基础URL
  timeout: 5000  # 请求超时时间（毫秒）
