server:
  port: ${EXECUTOR_PORT:8280}

spring:
  main:
    allow-circular-references: true
  application:
    name: ruleforge-executor

ruleforge:
  knowledgeUpdateCycleV2: 300
  isKnowledgeUpdateRemoteV2: true
  console:
    url: ${CONSOLE_URL:http://localhost:8180}
